# Generated by Django 4.2.3 on 2023-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_mileage',
            field=models.FloatField(default=0.0),
        ),
    ]
