services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env.prod
    # healthcheck for sever container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    image: ${DOCKERHUB_USERNAME}/csf-prod-server:latest
    container_name: csf_server
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - 8081:8081
    entrypoint: /entrypoint.sh
    volumes:
      - ./opt/accesslogs/:/var/log/accesslogs/
      - ./opt/static_files/:/static_files
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: csf_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/static_files:/opt/static_files
    depends_on:
      - server

  watchtower:
    image: containrrr/watchtower
    container_name: csf_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30