# Generated by Django 4.2.2 on 2023-06-25 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('join_code', models.CharField(default=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField()),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberOf', to='teams.team')),
            ],
        ),
    ]
