# Generated by Django 4.2.2 on 2023-07-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('subteam', '0002_subteam_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
