# Generated by Django 4.2.2 on 2023-07-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subteam', '0003_alter_subteam_team_id'),
        ('team', '0001_initial'),
        ('users', '0002_alter_user_subteam_id_alter_user_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subteam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subteam.subteam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
