# Generated by Django 4.2.2 on 2023-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_subteam_id_alter_user_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
