# Generated by Django 4.2.2 on 2023-07-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subteam', '0003_alter_subteam_team_id'),
        ('team', '0001_initial'),
        ('users', '0003_alter_user_subteam_id_alter_user_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subteam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subteam.subteam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_method',
            field=models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('WHEELING', 'WHEELING'), ('WALKING', 'WALKING')], max_length=100),
        ),
    ]
