# Generated by Django 4.2.2 on 2023-07-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_subteam_id_alter_user_team_id_and_more'),
        ('users', '0004_user_reset_time_user_reset_token'),
    ]

    operations = [
    ]
