# Generated by Django 4.2.3 on 2023-07-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
        ('users', '0006_user_challenge_start_date'),
    ]

    operations = [
    ]
