# Generated by Django 4.2.3 on 2023-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0006_user_avatar_0006_user_challenge_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='avatar1.jpg', max_length=100),
        ),
    ]
