# Generated by Django 4.2.3 on 2023-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_mileage',
            field=models.FloatField(default=0.0),
        ),
    ]
