# Generated by Django 4.2.3 on 2023-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[
                ('avatar 1', 'avatar 1'), ('avatar 2', 'avatar 2'), ('avatar 3', 'avatar 3'),
                ('avatar 4', 'avatar 4'), ('avatar 5', 'avatar 5'), ('avatar 6', 'avatar 6')], default='avatar1.jpg',
                max_length=100),
        ),
    ]