# Generated by Django 4.2.3 on 2023-07-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_total_mileage'),
        ('users', '0010_alter_user_avatar'),
    ]

    operations = [
    ]
