# Generated by Django 4.2.3 on 2023-07-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_total_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_mileage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
