# Generated by Django 4.2.2 on 2023-07-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('event', '0002_event_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
