# Generated by Django 4.2.2 on 2023-07-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='kilometres',
            field=models.FloatField(),
        ),
    ]
