# Generated by Django 4.2.3 on 2023-07-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_total_mileage'),
        ('mileage', '0003_alter_mileage_kilometres'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
